// World Cup 2026 Matches Database and Team Statistics
(function() {
  const INITIAL_MATCHES = [
    // --- PARTIDOS INAUGURALES ---
    {
      id: "m1",
      homeTeam: "México",
      homeCode: "MEX",
      homeFlag: "🇲🇽",
      awayTeam: "Sudáfrica",
      awayCode: "RSA",
      awayFlag: "🇿🇦",
      kickoff: "2026-06-11T17:00:00-06:00",
      group: "Grupo A",
      stadium: "Estadio Azteca, CDMX",
      realHomeGoals: null,
      realAwayGoals: null,
      status: "scheduled"
    },
    {
      id: "m2",
      homeTeam: "Corea del Sur",
      homeCode: "KOR",
      homeFlag: "🇰🇷",
      awayTeam: "Chequia",
      awayCode: "CZE",
      awayFlag: "🇨🇿",
      kickoff: "2026-06-11T20:30:00-06:00",
      group: "Grupo A",
      stadium: "Estadio Tres de Marzo, Guadalajara",
      realHomeGoals: null,
      realAwayGoals: null,
      status: "scheduled"
    },
    {
      id: "m3",
      homeTeam: "Canadá",
      homeCode: "CAN",
      homeFlag: "🇨🇦",
      awayTeam: "Bosnia y Herzegovina",
      awayCode: "BIH",
      awayFlag: "🇧🇦",
      kickoff: "2026-06-12T16:00:00-04:00",
      group: "Grupo B",
      stadium: "BMO Field, Toronto",
      realHomeGoals: null,
      realAwayGoals: null,
      status: "scheduled"
    },
    {
      id: "m4",
      homeTeam: "Estados Unidos",
      homeCode: "USA",
      homeFlag: "🇺🇸",
      awayTeam: "Paraguay",
      awayCode: "PAR",
      awayFlag: "🇵🇾",
      kickoff: "2026-06-12T19:30:00-07:00",
      group: "Grupo D",
      stadium: "SoFi Stadium, Inglewood",
      realHomeGoals: null,
      realAwayGoals: null,
      status: "scheduled"
    },
    // --- LUNES 22/6 ---
    {
      id: "m5",
      homeTeam: "Argentina",
      homeCode: "ARG",
      homeFlag: "🇦🇷",
      awayTeam: "Austria",
      awayCode: "AUT",
      awayFlag: "🇦🇹",
      kickoff: "2026-06-22T13:00:00-05:00",
      group: "Grupo J",
      stadium: "AT&T Stadium, Arlington",
      realHomeGoals: null,
      realAwayGoals: null,
      status: "scheduled"
    },
    {
      id: "m6",
      homeTeam: "Francia",
      homeCode: "FRA",
      homeFlag: "🇫🇷",
      awayTeam: "Irak",
      awayCode: "IRQ",
      awayFlag: "🇮🇶",
      kickoff: "2026-06-22T17:00:00-04:00",
      group: "Grupo I",
      stadium: "Lincoln Financial Field, Filadelfia",
      realHomeGoals: null,
      realAwayGoals: null,
      status: "scheduled"
    },
    {
      id: "m7",
      homeTeam: "Noruega",
      homeCode: "NOR",
      homeFlag: "🇳🇴",
      awayTeam: "Senegal",
      awayCode: "SEN",
      awayFlag: "🇸🇳",
      kickoff: "2026-06-22T20:00:00-04:00",
      group: "Grupo I",
      stadium: "MetLife Stadium, East Rutherford",
      realHomeGoals: null,
      realAwayGoals: null,
      status: "scheduled"
    },
    {
      id: "m8",
      homeTeam: "Jordania",
      homeCode: "JOR",
      homeFlag: "🇯🇴",
      awayTeam: "Argelia",
      awayCode: "ALG",
      awayFlag: "🇩🇿",
      kickoff: "2026-06-22T20:00:00-07:00",
      group: "Grupo J",
      stadium: "Levi's Stadium, Santa Clara",
      realHomeGoals: null,
      realAwayGoals: null,
      status: "scheduled"
    },
    // --- MARTES 23/6 ---
    {
      id: "m9",
      homeTeam: "Portugal",
      homeCode: "POR",
      homeFlag: "🇵🇹",
      awayTeam: "Uzbekistán",
      awayCode: "UZB",
      awayFlag: "🇺🇿",
      kickoff: "2026-06-23T13:00:00-04:00",
      group: "Grupo K",
      stadium: "Gillette Stadium, Boston",
      realHomeGoals: null,
      realAwayGoals: null,
      status: "scheduled"
    },
    {
      id: "m10",
      homeTeam: "Inglaterra",
      homeCode: "ENG",
      homeFlag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
      awayTeam: "Ghana",
      awayCode: "GHA",
      awayFlag: "🇬🇭",
      kickoff: "2026-06-23T16:00:00-05:00",
      group: "Grupo L",
      stadium: "Arrowhead Stadium, Kansas City",
      realHomeGoals: null,
      realAwayGoals: null,
      status: "scheduled"
    },
    {
      id: "m11",
      homeTeam: "Panamá",
      homeCode: "PAN",
      homeFlag: "🇵🇦",
      awayTeam: "Croacia",
      awayCode: "CRO",
      awayFlag: "🇭🇷",
      kickoff: "2026-06-23T19:00:00-04:00",
      group: "Grupo L",
      stadium: "Hard Rock Stadium, Miami",
      realHomeGoals: null,
      realAwayGoals: null,
      status: "scheduled"
    },
    {
      id: "m12",
      homeTeam: "Colombia",
      homeCode: "COL",
      homeFlag: "🇨🇴",
      awayTeam: "RD Congo",
      awayCode: "COD",
      awayFlag: "🇨🇩",
      kickoff: "2026-06-23T22:00:00-05:00",
      group: "Grupo K",
      stadium: "NRG Stadium, Houston",
      realHomeGoals: null,
      realAwayGoals: null,
      status: "scheduled"
    },
    // --- MIÉRCOLES 24/6 ---
    {
      id: "m13",
      homeTeam: "Suiza",
      homeCode: "SUI",
      homeFlag: "🇨🇭",
      awayTeam: "Canadá",
      awayCode: "CAN",
      awayFlag: "🇨🇦",
      kickoff: "2026-06-24T15:00:00-04:00",
      group: "Grupo B",
      stadium: "BMO Field, Toronto",
      realHomeGoals: null,
      realAwayGoals: null,
      status: "scheduled"
    },
    {
      id: "m14",
      homeTeam: "Bosnia y Herzegovina",
      homeCode: "BIH",
      homeFlag: "🇧🇦",
      awayTeam: "Catar",
      awayCode: "QAT",
      awayFlag: "🇶🇦",
      kickoff: "2026-06-24T15:00:00-05:00",
      group: "Grupo B",
      stadium: "Mercedes-Benz Stadium, Atlanta",
      realHomeGoals: null,
      realAwayGoals: null,
      status: "scheduled"
    },
    {
      id: "m15",
      homeTeam: "Marruecos",
      homeCode: "MAR",
      homeFlag: "🇲🇦",
      awayTeam: "Haití",
      awayCode: "HAI",
      awayFlag: "🇭🇹",
      kickoff: "2026-06-24T18:00:00-04:00",
      group: "Grupo C",
      stadium: "Subaru Park, Filadelfia",
      realHomeGoals: null,
      realAwayGoals: null,
      status: "scheduled"
    },
    {
      id: "m16",
      homeTeam: "Escocia",
      homeCode: "SCO",
      homeFlag: "🏴󠁧󠁢󠁳󠁣󠁴󠁿",
      awayTeam: "Brasil",
      awayCode: "BRA",
      awayFlag: "🇧🇷",
      kickoff: "2026-06-24T18:00:00-07:00",
      group: "Grupo C",
      stadium: "SoFi Stadium, Inglewood",
      realHomeGoals: null,
      realAwayGoals: null,
      status: "scheduled"
    },
    {
      id: "m17",
      homeTeam: "Sudáfrica",
      homeCode: "RSA",
      homeFlag: "🇿🇦",
      awayTeam: "Corea del Sur",
      awayCode: "KOR",
      awayFlag: "🇰🇷",
      kickoff: "2026-06-24T21:00:00-05:00",
      group: "Grupo A",
      stadium: "AT&T Stadium, Arlington",
      realHomeGoals: null,
      realAwayGoals: null,
      status: "scheduled"
    },
    {
      id: "m18",
      homeTeam: "Chequia",
      homeCode: "CZE",
      homeFlag: "🇨🇿",
      awayTeam: "México",
      awayCode: "MEX",
      awayFlag: "🇲🇽",
      kickoff: "2026-06-24T21:00:00-07:00",
      group: "Grupo A",
      stadium: "Estadio Azteca, CDMX",
      realHomeGoals: null,
      realAwayGoals: null,
      status: "scheduled"
    },
    // --- JUEVES 25/6 ---
    {
      id: "m19",
      homeTeam: "Curazao",
      homeCode: "CUW",
      homeFlag: "🇨🇼",
      awayTeam: "Costa de Marfil",
      awayCode: "CIV",
      awayFlag: "🇨🇮",
      kickoff: "2026-06-25T16:00:00-04:00",
      group: "Grupo E",
      stadium: "MetLife Stadium, East Rutherford",
      realHomeGoals: null,
      realAwayGoals: null,
      status: "scheduled"
    },
    {
      id: "m20",
      homeTeam: "Ecuador",
      homeCode: "ECU",
      homeFlag: "🇪🇨",
      awayTeam: "Alemania",
      awayCode: "GER",
      awayFlag: "🇩🇪",
      kickoff: "2026-06-25T16:00:00-07:00",
      group: "Grupo E",
      stadium: "Levi's Stadium, Santa Clara",
      realHomeGoals: null,
      realAwayGoals: null,
      status: "scheduled"
    },
    {
      id: "m21",
      homeTeam: "Túnez",
      homeCode: "TUN",
      homeFlag: "🇹🇳",
      awayTeam: "Países Bajos",
      awayCode: "NED",
      awayFlag: "🇳🇱",
      kickoff: "2026-06-25T19:00:00-04:00",
      group: "Grupo F",
      stadium: "Hard Rock Stadium, Miami",
      realHomeGoals: null,
      realAwayGoals: null,
      status: "scheduled"
    },
    {
      id: "m22",
      homeTeam: "Japón",
      homeCode: "JPN",
      homeFlag: "🇯🇵",
      awayTeam: "Suecia",
      awayCode: "SWE",
      awayFlag: "🇸🇪",
      kickoff: "2026-06-25T19:00:00-05:00",
      group: "Grupo F",
      stadium: "Mercedes-Benz Stadium, Atlanta",
      realHomeGoals: null,
      realAwayGoals: null,
      status: "scheduled"
    },
    {
      id: "m23",
      homeTeam: "Turquía",
      homeCode: "TUR",
      homeFlag: "🇹🇷",
      awayTeam: "Estados Unidos",
      awayCode: "USA",
      awayFlag: "🇺🇸",
      kickoff: "2026-06-25T22:00:00-05:00",
      group: "Grupo D",
      stadium: "NRG Stadium, Houston",
      realHomeGoals: null,
      realAwayGoals: null,
      status: "scheduled"
    },
    {
      id: "m24",
      homeTeam: "Paraguay",
      homeCode: "PAR",
      homeFlag: "🇵🇾",
      awayTeam: "Australia",
      awayCode: "AUS",
      awayFlag: "🇦🇺",
      kickoff: "2026-06-25T22:00:00-07:00",
      group: "Grupo D",
      stadium: "BC Place, Vancouver",
      realHomeGoals: null,
      realAwayGoals: null,
      status: "scheduled"
    },
    // --- VIERNES 26/6 ---
    {
      id: "m25",
      homeTeam: "Noruega",
      homeCode: "NOR",
      homeFlag: "🇳🇴",
      awayTeam: "Francia",
      awayCode: "FRA",
      awayFlag: "🇫🇷",
      kickoff: "2026-06-26T15:00:00-04:00",
      group: "Grupo I",
      stadium: "MetLife Stadium, East Rutherford",
      realHomeGoals: null,
      realAwayGoals: null,
      status: "scheduled"
    },
    {
      id: "m26",
      homeTeam: "Senegal",
      homeCode: "SEN",
      homeFlag: "🇸🇳",
      awayTeam: "Irak",
      awayCode: "IRQ",
      awayFlag: "🇮🇶",
      kickoff: "2026-06-26T15:00:00-04:00",
      group: "Grupo I",
      stadium: "Lincoln Financial Field, Filadelfia",
      realHomeGoals: null,
      realAwayGoals: null,
      status: "scheduled"
    },
    {
      id: "m27",
      homeTeam: "Cabo Verde",
      homeCode: "CPV",
      homeFlag: "🇨🇻",
      awayTeam: "Arabia Saudita",
      awayCode: "KSA",
      awayFlag: "🇸🇦",
      kickoff: "2026-06-26T20:00:00-05:00",
      group: "Grupo H",
      stadium: "AT&T Stadium, Arlington",
      realHomeGoals: null,
      realAwayGoals: null,
      status: "scheduled"
    },
    {
      id: "m28",
      homeTeam: "Uruguay",
      homeCode: "URU",
      homeFlag: "🇺🇾",
      awayTeam: "España",
      awayCode: "ESP",
      awayFlag: "🇪🇸",
      kickoff: "2026-06-26T20:00:00-04:00",
      group: "Grupo H",
      stadium: "Gillette Stadium, Boston",
      realHomeGoals: null,
      realAwayGoals: null,
      status: "scheduled"
    },
    {
      id: "m29",
      homeTeam: "Nueva Zelanda",
      homeCode: "NZL",
      homeFlag: "🇳🇿",
      awayTeam: "Bélgica",
      awayCode: "BEL",
      awayFlag: "🇧🇪",
      kickoff: "2026-06-26T23:00:00-07:00",
      group: "Grupo G",
      stadium: "SoFi Stadium, Inglewood",
      realHomeGoals: null,
      realAwayGoals: null,
      status: "scheduled"
    },
    {
      id: "m30",
      homeTeam: "Egipto",
      homeCode: "EGY",
      homeFlag: "🇪🇬",
      awayTeam: "Irán",
      awayCode: "IRN",
      awayFlag: "🇮🇷",
      kickoff: "2026-06-26T23:00:00-07:00",
      group: "Grupo G",
      stadium: "Lumen Field, Seattle",
      realHomeGoals: null,
      realAwayGoals: null,
      status: "scheduled"
    },
    // --- KNOCKOUT STAGE (Octavos - Llaves) ---
    {
      id: "k1",
      homeTeam: "1º Grupo I",
      homeCode: "1I",
      homeFlag: "❓",
      awayTeam: "2º Grupo J",
      awayCode: "2J",
      awayFlag: "❓",
      kickoff: "2026-06-28T15:00:00-04:00",
      group: "Octavos - Llave 1",
      stadium: "MetLife Stadium, East Rutherford",
      realHomeGoals: null,
      realAwayGoals: null,
      status: "scheduled",
      isKnockout: true,
      resolved: false,
      placeholderHome: "1I",
      placeholderAway: "2J"
    },
    {
      id: "k2",
      homeTeam: "1º Grupo K",
      homeCode: "1K",
      homeFlag: "❓",
      awayTeam: "2º Grupo L",
      awayCode: "2L",
      awayFlag: "❓",
      kickoff: "2026-06-28T19:00:00-05:00",
      group: "Octavos - Llave 2",
      stadium: "AT&T Stadium, Arlington",
      realHomeGoals: null,
      realAwayGoals: null,
      status: "scheduled",
      isKnockout: true,
      resolved: false,
      placeholderHome: "1K",
      placeholderAway: "2L"
    },
    {
      id: "k3",
      homeTeam: "1º Grupo A",
      homeCode: "1A",
      homeFlag: "❓",
      awayTeam: "2º Grupo B",
      awayCode: "2B",
      awayFlag: "❓",
      kickoff: "2026-06-29T15:00:00-04:00",
      group: "Octavos - Llave 3",
      stadium: "Hard Rock Stadium, Miami",
      realHomeGoals: null,
      realAwayGoals: null,
      status: "scheduled",
      isKnockout: true,
      resolved: false,
      placeholderHome: "1A",
      placeholderAway: "2B"
    },
    {
      id: "k4",
      homeTeam: "1º Grupo C",
      homeCode: "1C",
      homeFlag: "❓",
      awayTeam: "2º Grupo D",
      awayCode: "2D",
      awayFlag: "❓",
      kickoff: "2026-06-29T19:00:00-07:00",
      group: "Octavos - Llave 4",
      stadium: "SoFi Stadium, Inglewood",
      realHomeGoals: null,
      realAwayGoals: null,
      status: "scheduled",
      isKnockout: true,
      resolved: false,
      placeholderHome: "1C",
      placeholderAway: "2D"
    },
    {
      id: "k5",
      homeTeam: "1º Grupo E",
      homeCode: "1E",
      homeFlag: "❓",
      awayTeam: "2º Grupo F",
      awayCode: "2F",
      awayFlag: "❓",
      kickoff: "2026-06-30T15:00:00-04:00",
      group: "Octavos - Llave 5",
      stadium: "Gillette Stadium, Boston",
      realHomeGoals: null,
      realAwayGoals: null,
      status: "scheduled",
      isKnockout: true,
      resolved: false,
      placeholderHome: "1E",
      placeholderAway: "2F"
    },
    {
      id: "k6",
      homeTeam: "1º Grupo G",
      homeCode: "1G",
      homeFlag: "❓",
      awayTeam: "2º Grupo H",
      awayCode: "2H",
      awayFlag: "❓",
      kickoff: "2026-06-30T19:00:00-05:00",
      group: "Octavos - Llave 6",
      stadium: "NRG Stadium, Houston",
      realHomeGoals: null,
      realAwayGoals: null,
      status: "scheduled",
      isKnockout: true,
      resolved: false,
      placeholderHome: "1G",
      placeholderAway: "2H"
    }
  ];

  const TEAM_STATS = {
    "Argentina": { participations: 18, titles: 3, bestResult: "Campeón (1978, 1986, 2022)", attack: 93, defense: 89, overview: "La 'Albiceleste' defiende la corona mundial con un plantel repleto de figuras consagradas." },
    "Austria": { participations: 7, titles: 0, bestResult: "Tercer lugar (1954)", attack: 79, defense: 78, overview: "Una selección europea sólida y ordenada tácticamente." },
    "Francia": { participations: 16, titles: 2, bestResult: "Campeón (1998, 2018)", attack: 92, defense: 91, overview: "Los 'Bleus' combinan velocidad física extrema, profundidad letal y gran jerarquía." },
    "Irak": { participations: 1, titles: 0, bestResult: "Fase de grupos (1986)", attack: 70, defense: 68, overview: "La escuadra asiática busca dar la gran sorpresa en el torneo internacional." },
    "Noruega": { participations: 3, titles: 0, bestResult: "Octavos de final (1998)", attack: 84, defense: 77, overview: "Liderados por Erling Haaland en el ataque, buscan ser la gran sorpresa europea." },
    "Senegal": { participations: 3, titles: 0, bestResult: "Cuartos de final (2002)", attack: 81, defense: 82, overview: "Los Leones de la Teranga combinan potencia física y experiencia internacional." },
    "Jordania": { participations: 0, titles: 0, bestResult: "Debutante", attack: 68, defense: 66, overview: "Debutan en el máximo torneo buscando escribir historia en su primera participación." },
    "Argelia": { participations: 4, titles: 0, bestResult: "Octavos de final (2014)", attack: 78, defense: 76, overview: "Selección del norte de África veloz y con un mediocampo altamente dinámico." },
    "Portugal": { participations: 8, titles: 0, bestResult: "Tercer lugar (1966)", attack: 88, defense: 84, overview: "Una constelación de talento ofensivo luso busca coronarse en América." },
    "Uzbekistán": { participations: 0, titles: 0, bestResult: "Debutante", attack: 71, defense: 70, overview: "Debutan en la copa mundial tras un gran proceso clasificatorio en Asia." },
    "Inglaterra": { participations: 16, titles: 1, bestResult: "Campeón (1966)", attack: 90, defense: 88, overview: "La cuna del fútbol llega con un plantel estelar y la presión de llevar la copa a casa." },
    "Ghana": { participations: 4, titles: 0, bestResult: "Cuartos de final (2010)", attack: 77, defense: 75, overview: "Las 'Estrellas Negras' destacan por su potencia física y velocidad en transiciones." },
    "Panamá": { participations: 1, titles: 0, bestResult: "Fase de grupos (2018)", attack: 72, defense: 71, overview: "Los 'Canaleros' regresan al mundial con una plantilla experimentada y unida." },
    "Croacia": { participations: 6, titles: 0, bestResult: "Subcampeón (2018)", attack: 83, defense: 84, overview: "Los balcánicos destacan por su control del mediocampo y resiliencia mental." },
    "Colombia": { participations: 6, titles: 0, bestResult: "Cuartos de final (2014)", attack: 84, defense: 80, overview: "El equipo cafetero destaca por su buen trato de balón y velocidad en bandas." },
    "RD Congo": { participations: 1, titles: 0, bestResult: "Fase de grupos (1974)", attack: 73, defense: 71, overview: "Los 'Leopardos' retornan buscando hacer valer su potencia física africana." },
    "Suiza": { participations: 12, titles: 0, bestResult: "Cuartos de final (1934, 1938, 1954)", attack: 80, defense: 81, overview: "Un equipo altamente ordenado con gran disciplina táctica y solidez." },
    "Canadá": { participations: 2, titles: 0, bestResult: "Fase de grupos (1986, 2022)", attack: 77, defense: 74, overview: "Liderados por Alphonso Davies, buscan hacer valer su localía." },
    "Bosnia y Herzegovina": { participations: 1, titles: 0, bestResult: "Fase de grupos (2014)", attack: 75, defense: 74, overview: "Un conjunto europeo con gran temperamento y excelente juego aéreo." },
    "Catar": { participations: 1, titles: 0, bestResult: "Fase de grupos (2022)", attack: 72, defense: 70, overview: "El campeón de Asia busca consolidar su crecimiento deportivo a nivel mundial." },
    "Marruecos": { participations: 6, titles: 0, bestResult: "Cuarto lugar (2022)", attack: 81, defense: 85, overview: "La revelación de Qatar 2022 busca confirmar su estatus como potencia global." },
    "Haití": { participations: 1, titles: 0, bestResult: "Fase de grupos (1974)", attack: 67, defense: 65, overview: "Los caribeños vuelven a la cita mundialista con mucha ilusión y entrega física." },
    "Escocia": { participations: 8, titles: 0, bestResult: "Fase de grupos", attack: 76, defense: 77, overview: "Una escuadra británica combativa, caracterizada por su entrega y juego físico." },
    "Brasil": { participations: 22, titles: 5, bestResult: "Campeón (1958, 1962, 1970, 1994, 2002)", attack: 94, defense: 87, overview: "La única selección con asistencia perfecta busca su ansiado hexacampeonato." },
    "Sudáfrica": { participations: 3, titles: 0, bestResult: "Fase de grupos (1998, 2002, 2010)", attack: 73, defense: 72, overview: "Los 'Bafana Bafana' regresan motivados a la escena internacional." },
    "Corea del Sur": { participations: 11, titles: 0, bestResult: "Cuarto lugar (2002)", attack: 78, defense: 76, overview: "Un juego dinámico e incansable define a los guerreros coreanos." },
    "Chequia": { participations: 9, titles: 0, bestResult: "Subcampeón (1934, 1962)", attack: 79, defense: 77, overview: "Una selección europea caracterizada por su disciplina e inteligencia táctica." },
    "México": { participations: 17, titles: 0, bestResult: "Cuartos de final (1970, 1986)", attack: 78, defense: 75, overview: "El gigante de la Concacaf busca superar la barrera del quinto partido como local." },
    "Curazao": { participations: 0, titles: 0, bestResult: "Debutante", attack: 70, defense: 69, overview: "La gran sorpresa caribeña del torneo hace su histórica presentación." },
    "Costa de Marfil": { participations: 3, titles: 0, bestResult: "Fase de grupos (2006, 2010, 2014)", attack: 81, defense: 78, overview: "Los elefantes marfileños combinan talento técnico y gran resistencia." },
    "Ecuador": { participations: 4, titles: 0, bestResult: "Octavos de final (2006)", attack: 80, defense: 82, overview: "La Tri destaca por su juventud, gran despliegue físico y orden táctico." },
    "Alemania": { participations: 20, titles: 4, bestResult: "Campeón (1954, 1974, 1990, 2014)", attack: 88, defense: 85, overview: "La 'Mannschaft' representa la eficiencia competitiva buscando su quinta estrella." },
    "Túnez": { participations: 6, titles: 0, bestResult: "Fase de grupos", attack: 74, defense: 76, overview: "Las Águilas de Cartago destacan por su férrea defensa y contragolpe letal." },
    "Países Bajos": { participations: 11, titles: 0, bestResult: "Subcampeón (1974, 1978, 2010)", attack: 87, defense: 89, overview: "La 'Naranja Mecánica' busca al fin coronar su historia con el título mundial." },
    "Japón": { participations: 7, titles: 0, bestResult: "Octavos de final", attack: 82, defense: 81, overview: "Samuráis Azules con transiciones rápidas y gran disciplina táctica." },
    "Suecia": { participations: 12, titles: 0, bestResult: "Subcampeón (1958)", attack: 80, defense: 79, overview: "Conjunto escandinavo de gran talla física y juego aéreo dominante." },
    "Turquía": { participations: 2, titles: 0, bestResult: "Tercer lugar (2002)", attack: 81, defense: 78, overview: "Una escuadra turca caracterizada por su pasión, garra y gran técnica individual." },
    "Estados Unidos": { participations: 11, titles: 0, bestResult: "Tercer lugar (1930)", attack: 83, defense: 80, overview: "Los estadounidenses quieren consolidar su crecimiento en casa." },
    "Paraguay": { participations: 8, titles: 0, bestResult: "Cuartos de final (2010)", attack: 76, defense: 80, overview: "La escuadra guaraní destaca por su garra, juego aéreo y solidez defensiva." },
    "Australia": { participations: 6, titles: 0, bestResult: "Octavos de final (2006, 2022)", attack: 75, defense: 76, overview: "Los 'Socceroos' son incansables, con juego físico y vertical." },
    "Cabo Verde": { participations: 0, titles: 0, bestResult: "Debutante", attack: 71, defense: 70, overview: "Los Tiburones Azules debutan con orgullo representando al fútbol isleño africano." },
    "Arabia Saudita": { participations: 6, titles: 0, bestResult: "Octavos de final (1994)", attack: 73, defense: 71, overview: "Hijos del desierto veloces y tácticos, listos para plantar cara." },
    "Uruguay": { participations: 14, titles: 2, bestResult: "Campeón (1930, 1950)", attack: 85, defense: 86, overview: "La Celeste de Marcelo Bielsa destaca por su presión asfixiante y mística." },
    "España": { participations: 16, titles: 1, bestResult: "Campeón (2010)", attack: 89, defense: 86, overview: "La Roja domina la posesión y desborda por bandas con juventud." },
    "Nueva Zelanda": { participations: 2, titles: 0, bestResult: "Fase de grupos (1982, 2010)", attack: 68, defense: 71, overview: "All Whites buscando repetir la hazaña histórica de Sudáfrica 2010." },
    "Bélgica": { participations: 14, titles: 0, bestResult: "Tercer lugar (2018)", attack: 85, defense: 81, overview: "Los Diablos Rojos combinan talento veterano con jóvenes promesas europeas." },
    "Egipto": { participations: 3, titles: 0, bestResult: "Fase de grupos", attack: 79, defense: 76, overview: "Los faraones buscan avanzar de ronda liderados por su velocidad ofensiva." },
    "Irán": { participations: 6, titles: 0, bestResult: "Fase de grupos", attack: 75, defense: 76, overview: "Un conjunto defensivamente muy disciplinado y letal al contragolpe." }
  };

  // A match is lockable if the current time is less than 1 hour before kickoff.
  // currentSimulatedTime is a millisecond timestamp representing simulated time.
  function isMatchLocked(match, currentSimulatedTime) {
    const kickoffTime = new Date(match.kickoff).getTime();
    const oneHourInMs = 60 * 60 * 1000;
    return (kickoffTime - currentSimulatedTime) <= oneHourInMs;
  }

  // Helper to format kickoff dates
  function formatMatchTime(kickoffStr) {
    const date = new Date(kickoffStr);
    const lang = localStorage.getItem("wc_lang") || "es";
    const locale = lang === "en" ? "en-US" : "es-ES";
    return date.toLocaleString(locale, {
      weekday: 'short',
      month: 'short',
      day: 'numeric',
      hour: '2-digit',
      minute: '2-digit',
      hour12: false
    });
  }

  window.WC_DATA = {
    INITIAL_MATCHES,
    TEAM_STATS,
    isMatchLocked,
    formatMatchTime
  };
})();
